import { Listing, ProductCategory, HaatMarket, Order } from '../types';

export const INITIAL_CATEGORIES: ProductCategory[] = [
  { id: '1', slug: 'rice', name_en: 'Joha & Bora Rice', name_as: 'জোহা আৰু বৰা ধান', icon: 'wheat' },
  { id: '2', slug: 'silk', name_en: 'Muga & Eri Silk', name_as: 'মুগা আৰু এৰী কাপোৰ', icon: 'sparkles' },
  { id: '3', slug: 'bamboo', name_en: 'Bamboo & Cane', name_as: 'বাঁহ-বেতৰ শিল্প', icon: 'hammer' },
  { id: '4', slug: 'tea', name_en: 'CTC & Orthodox Tea', name_as: 'অসম চাহপাত', icon: 'coffee' },
  { id: '5', slug: 'fish', name_en: 'River Fish & Shutki', name_as: 'লোকেল মাছ আৰু শুকতি', icon: 'fish' },
  { id: '6', slug: 'vegetables', name_en: 'Organic Vegetables', name_as: 'সতেজ থলুৱা শাক-পাচলি', icon: 'salad' },
  { id: '7', slug: 'spices', name_en: 'Bhut Jolokia & Spices', name_as: 'ভোট জলকীয়া আৰু মচলা', icon: 'flame' },
  { id: '8', slug: 'dairy', name_en: 'Pure Buffalo Ghee', name_as: 'ম’হৰ খাঁটি ঘিউ-দৈ', icon: 'cup-soda' },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'l1',
    seller_id: 's1',
    seller_name: 'Pragjyotishpur Mahila SHG',
    seller_type: 'shg_member',
    seller_phone: '+91 94350 12345',
    category_id: '1',
    category_name_en: 'Joha & Bora Rice',
    category_name_as: 'জোহা আৰু বৰা ধান',
    title_en: 'Kola Joha Aromatic Rice (A-Grade)',
    title_as: 'সুগন্ধি ক’লা জোহা চাউল (প্ৰথম শ্ৰেণী)',
    description_en: 'Directly sourced from organic paddy fields of Darrang. Naturally fragrant, soft grain, chemical-free polishing.',
    description_as: 'দৰঙৰ জৈৱিক ধাননিৰ পৰা সংগৃহীত সুগন্ধি জোহা চাউল। কোনো ৰাসায়নিক ঔষধ অবিহনে প্ৰস্তুত।',
    price: 120,
    unit: 'kg',
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    lat: 26.4350,
    lng: 92.0300,
    village: 'Deomornoi',
    district: 'Darrang',
    haat_name: 'Mangaldai Weekly Haat',
    distance_km: 2.8,
    rating: 4.8,
    status: 'active',
    is_organic: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l2',
    seller_id: 's2',
    seller_name: 'Sualkuchi Weavers Collective',
    seller_type: 'small_business',
    seller_phone: '+91 98640 54321',
    category_id: '2',
    category_name_en: 'Muga & Eri Silk',
    category_name_as: 'মুগা আৰু এৰী কাপোৰ',
    title_en: 'Handwoven Pure Muga Silk Mekhela Sador',
    title_as: 'হাতশালত বোৱা খাঁটি সোণালী মুগা মেখেলা চাদৰ',
    description_en: 'Authentic GI-tagged Golden Silk hand-woven on traditional looms with intricate Kingkhap motifs.',
    description_as: 'পৰম্পৰাগত কিংকাপ চানেকীৰে বোৱা জিআই স্বীকৃতিপ্ৰাপ্ত সোণালী মুগা মেখেলা চাদৰ।',
    price: 8500,
    unit: 'piece',
    stock: 6,
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    lat: 26.1700,
    lng: 91.5700,
    village: 'Bamunpara',
    district: 'Kamrup Rural',
    haat_name: 'Sualkuchi Silk Haat',
    distance_km: 7.4,
    rating: 4.9,
    status: 'active',
    is_organic: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l3',
    seller_id: 's3',
    seller_name: 'Barpeta Bamboo Crafts Guild',
    seller_type: 'shg_member',
    seller_phone: '+91 97060 99881',
    category_id: '3',
    category_name_en: 'Bamboo & Cane',
    category_name_as: 'বাঁহ-বেতৰ শিল্প',
    title_en: 'Traditional Assamese Japi (Decor & Sun Hat)',
    title_as: 'অসমীয়া পৰম্পৰাগত ফুলাম জাপি',
    description_en: 'Handcrafted with seasoned bamboo strips and red-bordered Tokow pat. Premium village craftsmanship.',
    description_as: 'টোকৌ পাত আৰু বাঁহেৰে নিৰ্মিত ফুলাম ফুল-জাপি। ঘৰ সজোৱাৰ বাবে অতি উত্তম।',
    price: 350,
    unit: 'piece',
    stock: 20,
    image_url: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=600&q=80',
    lat: 26.3200,
    lng: 91.0000,
    village: 'Sarthebari',
    district: 'Barpeta',
    distance_km: 12.1,
    rating: 4.7,
    status: 'active',
    is_organic: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l4',
    seller_id: 's4',
    seller_name: 'Sonitpur Organic Growers',
    seller_type: 'individual',
    seller_phone: '+91 91010 33445',
    category_id: '4',
    category_name_en: 'CTC & Orthodox Tea',
    category_name_as: 'অসম চাহপাত',
    title_en: 'Handmade Smallholder Orthodox Green Tea',
    title_as: 'ক্ষুদ্ৰ চাহ খেতিয়কৰ হাতত প্ৰস্তুত গ্ৰীন টি',
    description_en: 'Single-estate whole-leaf orthodox tea hand-plucked from pesticide-free homestead tea garden.',
    description_as: 'কীটনাশক মুক্ত ঘৰুৱা চাহ বাগিচাৰ পৰা সংগ্ৰহ কৰা সতেজ সেউজীয়া চাহপাত।',
    price: 280,
    unit: '250g pack',
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    lat: 26.6300,
    lng: 92.7900,
    village: 'Dhekiajuli',
    district: 'Sonitpur',
    distance_km: 18.5,
    rating: 4.9,
    status: 'active',
    is_organic: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l5',
    seller_id: 's5',
    seller_name: 'Brahmaputra Fishermen Society',
    seller_type: 'shg_member',
    seller_phone: '+91 94351 77665',
    category_id: '5',
    category_name_en: 'River Fish & Shutki',
    category_name_as: 'লোকেল মাছ আৰু শুকতি',
    title_en: 'Fresh Brahmaputra Chitol Fish',
    title_as: 'ব্ৰহ্মপুত্ৰৰ সতেজ ডাঙৰ চিতল মাছ',
    description_en: 'Caught this morning from fresh Brahmaputra waters. Cut and cleaned upon order.',
    description_as: 'আজি ৰাতিপুৱা ধৰা ব্ৰহ্মপুত্ৰৰ সতেজ চিতল মাছ। অৰ্ডাৰ দিলে কাটি পৰিষ্কাৰ কৰি দিয়া হ’ব।',
    price: 650,
    unit: 'kg',
    stock: 12,
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    lat: 26.1800,
    lng: 91.7500,
    village: 'Uzanbazar Ghat',
    district: 'Kamrup Metro',
    haat_name: 'Uzanbazar Daily Fish Haat',
    distance_km: 4.2,
    rating: 4.9,
    status: 'active',
    is_organic: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l6',
    seller_id: 's6',
    seller_name: 'Darrang Agro Producers Co-op',
    seller_type: 'shg_member',
    seller_phone: '+91 98540 11223',
    category_id: '7',
    category_name_en: 'Bhut Jolokia & Spices',
    category_name_as: 'ভোট জলকীয়া আৰু মচলা',
    title_en: 'Sun-dried Organic Bhut Jolokia (Ghost Pepper)',
    title_as: 'ৰ’দত শুকোৱা থলুৱা ভোট জলকীয়া',
    description_en: 'Extreme heat, natural sun-cured Bhut Jolokia directly from the fields of Kharupetia.',
    description_as: 'খাৰুপেটীয়াৰ পথাৰৰ পৰা সতেজ সংগ্ৰহ কৰি ৰ’দত শুকোৱা অতিকৈ জ্বলা ভোট জলকীয়া।',
    price: 150,
    unit: '100g pack',
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
    lat: 26.5100,
    lng: 92.1300,
    village: 'Kharupetia',
    district: 'Darrang',
    distance_km: 8.9,
    rating: 4.6,
    status: 'active',
    is_organic: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_HAATS: HaatMarket[] = [
  {
    id: 'h1',
    name_en: 'Mangaldai Bi-Weekly Haat',
    name_as: 'মঙলদৈ দ্বি-সাপ্তাহিক হাট',
    district: 'Darrang',
    location: 'Mangaldai Town Market Field',
    market_day: 'Every Wednesday & Saturday',
    market_day_as: 'প্ৰতি বুধবাৰ আৰু শনিবাৰ',
    timings: '6:00 AM - 4:00 PM',
    specialty_en: 'Fresh vegetables, Joha rice, livestock & bamboo baskets',
    specialty_as: 'সতেজ শাক-পাচলি, জোহা চাউল, হাঁহ-কুকুৰা আৰু বাঁহৰ সামগ্ৰী',
    active_sellers_count: 140,
    lat: 26.4380,
    lng: 92.0350,
    distance_km: 1.8,
    image_url: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'h2',
    name_en: 'Jagiroad Dry Fish Haat (Asia’s Largest)',
    name_as: 'জাগীৰোড শুকান মাছৰ হাট (এছিয়াৰ বৃহত্তম)',
    district: 'Morigaon',
    location: 'Jagiroad Railway Market Complex',
    market_day: 'Every Thursday, Friday & Saturday',
    market_day_as: 'প্ৰতি বৃহস্পতি, শুক্ৰ আৰু শনিবাৰ',
    timings: '4:00 AM - 1:00 PM',
    specialty_en: '100+ indigenous river & wetland dried fish varieties',
    specialty_as: '১০০ৰো অধিক থলুৱা শুকান মাছ (শুকতি) আৰু সতেজ মাছ',
    active_sellers_count: 320,
    lat: 26.1200,
    lng: 92.2100,
    distance_km: 19.5,
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'h3',
    name_en: 'Sualkuchi Silk Weavers Haat',
    name_as: 'শুৱালকুছি পাট-মুগা হাট',
    district: 'Kamrup Rural',
    location: 'Silk Village Central Mandi',
    market_day: 'Every Sunday',
    market_day_as: 'প্ৰতি দেওবাৰ',
    timings: '7:00 AM - 6:00 PM',
    specialty_en: 'Direct weaver-to-buyer Muga, Eri, and Paat silk fabrics',
    specialty_as: 'তাঁতীৰ পৰা পোনে পোনে খাঁটি মুগা, এৰী আৰু পাট কাপোৰ',
    active_sellers_count: 85,
    lat: 26.1750,
    lng: 91.5720,
    distance_km: 14.2,
    image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    order_number: '#TB-8842',
    buyer_id: 'b1',
    buyer_name: 'John Doe',
    buyer_phone: '+91 98765 43210',
    seller_id: 's1',
    seller_name: 'Pragjyotishpur Mahila SHG',
    seller_phone: '+91 94350 12345',
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-101',
        listing_id: 'l1',
        title: 'Kola Joha Aromatic Rice',
        quantity: 2,
        unit_price: 120,
        unit: 'kg',
        line_total: 240,
        image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'oi-2',
        order_id: 'ord-101',
        listing_id: 'l6',
        title: 'Sun-dried Organic Bhut Jolokia',
        quantity: 1,
        unit_price: 150,
        unit: '100g pack',
        line_total: 150,
        image_url: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
      }
    ],
    subtotal: 390,
    delivery_fee: 0,
    discount: 0,
    total: 390,
    status: 'REQUESTED',
    pickup_or_delivery: 'delivery',
    delivery_address: 'Ward No 4, Hospital Road, Mangaldai - 784125',
    payment_method: 'upi',
    payment_status: 'paid',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    estimated_delivery: 'Today, within 2 hours',
  },
  {
    id: 'ord-102',
    order_number: '#TB-8840',
    buyer_id: 'b1',
    buyer_name: 'Priya Sharma',
    buyer_phone: '+91 98765 43210',
    seller_id: 's3',
    seller_name: 'Barpeta Bamboo Crafts Guild',
    seller_phone: '+91 97060 99881',
    items: [
      {
        id: 'oi-3',
        order_id: 'ord-102',
        listing_id: 'l3',
        title: 'Traditional Assamese Japi',
        quantity: 2,
        unit_price: 350,
        unit: 'piece',
        line_total: 700,
        image_url: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=600&q=80',
      }
    ],
    subtotal: 700,
    delivery_fee: 40,
    discount: 0,
    total: 740,
    status: 'ACCEPTED',
    pickup_or_delivery: 'delivery',
    delivery_address: 'Barpeta Town, Ward 2',
    payment_method: 'cod',
    payment_status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    estimated_delivery: 'Tomorrow Morning',
  }
];
